version: '3.6'

services: 
  database:
    image: 'postgres'
    container_name: 'pg'
    ports: 
      - 5432:5432
    environment: 
      POSTGRESS_DB: 'teste'
      POSTGRESS_USERNAME: 'teste'
      POSTGRESS_PASSWORD: 'teste'